server:
  port: 8761
  
spring:
  application:
    name: AMAZAON_SERVER

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
 