server:
  port: 8012
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: SHOPPING-SERVICE